# Generated by Django 2.0.2 on 2018-03-15 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat_choices',
            field=models.CharField(choices=[('chat01', 'chat01'), ('chat02', 'chat02'), ('chat03', 'chat03'), ('chat04', 'chat04')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
